In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

In [2]:
traindata=pd.read_csv(r"C:\Users\TCS\Downloads\bneg.csv ",delimiter=",")
testdata=pd.read_csv(r"C:\Users\TCS\Downloads\bnegtest.csv",delimiter=",")


In [3]:
traindata

B  All India Institute of Medical Sciences (AIIMS)  \
0  8                                                1   
1  8                                                1   
2  8                                                1   
3  8                                                1   
4  8                                                1   
5  8                                                1   
6  8                                                1   
7  8                                                0   

   Armed Forces Transfusion Centre  Dr. Ram Manohar Lohia Hospital  \
0                                1                               0   
1                                1                               1   
2                                1                               1   
3                                0                               1   
4                                0                               1   
5                                1                               1   
6                                1                               1   
7                                0                               0   

   E.S.I. Hospital  Safdarjung Hospital  Sucheta Kriplani Hospital  \
0                1                    1                          0   
1                1                    0                          0   
2                1                    0                          1   
3                0                    0                          1   
4                1                    0                          1   
5                1                    1                          0   
6                0                    0                          0   
7                1                    1                          0   

   Govind Ballabh Pant Hospital  Guru Tegh Bahadur Hospital  \
0                             0                           0   
1                             1                           1   
2                             1                           0   
3                             1                           1   
4                             1                           1   
5                             1                           1   
6                             1                           1   
7                             0                           0   

   Regional Blood tranfusion Center of Central zone  
0                                                 1  
1                                                 0  
2                                                 1  
3                                                 0  
4                                                 1  
5                                                 1  
6                                                 0  
7                                                 1

In [4]:
df=pd.DataFrame(traindata)
df

B  All India Institute of Medical Sciences (AIIMS)  \
0  8                                                1   
1  8                                                1   
2  8                                                1   
3  8                                                1   
4  8                                                1   
5  8                                                1   
6  8                                                1   
7  8                                                0   

   Armed Forces Transfusion Centre  Dr. Ram Manohar Lohia Hospital  \
0                                1                               0   
1                                1                               1   
2                                1                               1   
3                                0                               1   
4                                0                               1   
5                                1                               1   
6                                1                               1   
7                                0                               0   

   E.S.I. Hospital  Safdarjung Hospital  Sucheta Kriplani Hospital  \
0                1                    1                          0   
1                1                    0                          0   
2                1                    0                          1   
3                0                    0                          1   
4                1                    0                          1   
5                1                    1                          0   
6                0                    0                          0   
7                1                    1                          0   

   Govind Ballabh Pant Hospital  Guru Tegh Bahadur Hospital  \
0                             0                           0   
1                             1                           1   
2                             1                           0   
3                             1                           1   
4                             1                           1   
5                             1                           1   
6                             1                           1   
7                             0                           0   

   Regional Blood tranfusion Center of Central zone  
0                                                 1  
1                                                 0  
2                                                 1  
3                                                 0  
4                                                 1  
5                                                 1  
6                                                 0  
7                                                 1

In [5]:
xtrain=df.drop(['All India Institute of Medical Sciences (AIIMS)','Armed Forces Transfusion Centre','Dr. Ram Manohar Lohia Hospital','E.S.I. Hospital','Safdarjung Hospital','Sucheta Kriplani Hospital','Govind Ballabh Pant Hospital','Guru Tegh Bahadur Hospital','Regional Blood tranfusion Center of Central zone'],axis=1)
xtrain.shape

(8, 1)

In [6]:
y1train=df["All India Institute of Medical Sciences (AIIMS)"]
y1train

0    1
1    1
2    1
3    1
4    1
5    1
6    1
7    0
Name: All India Institute of Medical Sciences (AIIMS), dtype: int64

In [7]:
y2train=df["Armed Forces Transfusion Centre"]
y3train=df["Dr. Ram Manohar Lohia Hospital"]
y4train=df["E.S.I. Hospital"]
y5train=df["Safdarjung Hospital"]
y6train=df["Sucheta Kriplani Hospital"]
y7train=df["Govind Ballabh Pant Hospital"]
y8train=df["Guru Tegh Bahadur Hospital"]
y9train=df["Regional Blood tranfusion Center of Central zone"]


In [8]:
testdata

B  All India Institute of Medical Sciences (AIIMS)  \
0  8                                                1   
1  8                                                0   
2  8                                                1   
3  8                                                0   
4  8                                                0   
5  8                                                1   
6  8                                                1   
7  8                                                0   

   Armed Forces Transfusion Centre  Dr. Ram Manohar Lohia Hospital  \
0                                1                               1   
1                                1                               1   
2                                0                               0   
3                                0                               1   
4                                1                               0   
5                                0                               1   
6                                1                               1   
7                                1                               1   

   E.S.I. Hospital  Safdarjung Hospital  Sucheta Kriplani Hospital  \
0                1                    0                          1   
1                0                    1                          0   
2                1                    0                          1   
3                1                    1                          0   
4                1                    1                          1   
5                0                    1                          0   
6                0                    0                          1   
7                1                    1                          0   

   Govind Ballabh Pant Hospital  Guru Tegh Bahadur Hospital  \
0                             0                           1   
1                             1                           1   
2                             0                           0   
3                             1                           1   
4                             0                           0   
5                             1                           0   
6                             1                           0   
7                             1                           0   

   Regional Blood tranfusion Center of Central zone  
0                                                 0  
1                                                 1  
2                                                 1  
3                                                 0  
4                                                 1  
5                                                 1  
6                                                 0  
7                                                 0

In [9]:
df2=pd.DataFrame(testdata)
df2

B  All India Institute of Medical Sciences (AIIMS)  \
0  8                                                1   
1  8                                                0   
2  8                                                1   
3  8                                                0   
4  8                                                0   
5  8                                                1   
6  8                                                1   
7  8                                                0   

   Armed Forces Transfusion Centre  Dr. Ram Manohar Lohia Hospital  \
0                                1                               1   
1                                1                               1   
2                                0                               0   
3                                0                               1   
4                                1                               0   
5                                0                               1   
6                                1                               1   
7                                1                               1   

   E.S.I. Hospital  Safdarjung Hospital  Sucheta Kriplani Hospital  \
0                1                    0                          1   
1                0                    1                          0   
2                1                    0                          1   
3                1                    1                          0   
4                1                    1                          1   
5                0                    1                          0   
6                0                    0                          1   
7                1                    1                          0   

   Govind Ballabh Pant Hospital  Guru Tegh Bahadur Hospital  \
0                             0                           1   
1                             1                           1   
2                             0                           0   
3                             1                           1   
4                             0                           0   
5                             1                           0   
6                             1                           0   
7                             1                           0   

   Regional Blood tranfusion Center of Central zone  
0                                                 0  
1                                                 1  
2                                                 1  
3                                                 0  
4                                                 1  
5                                                 1  
6                                                 0  
7                                                 0

In [10]:
xtest=df2.drop(['All India Institute of Medical Sciences (AIIMS)','Armed Forces Transfusion Centre','Dr. Ram Manohar Lohia Hospital','E.S.I. Hospital','Safdarjung Hospital','Sucheta Kriplani Hospital','Govind Ballabh Pant Hospital','Guru Tegh Bahadur Hospital','Regional Blood tranfusion Center of Central zone'],axis=1)
xtest.shape

(8, 1)

In [11]:
y1test=df2["All India Institute of Medical Sciences (AIIMS)"]
y1test

0    1
1    0
2    1
3    0
4    0
5    1
6    1
7    0
Name: All India Institute of Medical Sciences (AIIMS), dtype: int64

In [12]:
y2test=df2["Armed Forces Transfusion Centre"]
y3test=df2["Dr. Ram Manohar Lohia Hospital"]
y4test=df2["E.S.I. Hospital"]
y5test=df2["Safdarjung Hospital"]
y6test=df2["Sucheta Kriplani Hospital"]
y7test=df2["Govind Ballabh Pant Hospital"]
y8test=df2["Guru Tegh Bahadur Hospital"]
y9test=df2["Regional Blood tranfusion Center of Central zone"]


In [13]:
cl=RandomForestClassifier(random_state=0)
cl.fit(xtrain,y1train)
ypred1=cl.predict(xtest)
print(ypred1)
print("THE PERCENTAGE OF FINDING THE BLOOD GROUP A+ In AIIMS IS")
w=(accuracy_score(y1test, ypred1))
print(w*100)




[1 1 1 1 1 1 1 1]
THE PERCENTAGE OF FINDING THE BLOOD GROUP A+ In AIIMS IS
50.0


C:\anaconda\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [14]:
c=RandomForestClassifier(random_state=0)
c.fit(xtrain,y2train)
ypred2=c.predict(xtest)
print(ypred2)
print("THE PERCENTAGE OF FINDING THE BLOOD GROUP A+ In ARMED FORCES IS")
p=(accuracy_score(y2test, ypred2))
print(p*100)


[1 1 1 1 1 1 1 1]
THE PERCENTAGE OF FINDING THE BLOOD GROUP A+ In ARMED FORCES IS
62.5


C:\anaconda\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [15]:
l=RandomForestClassifier(random_state=0)
l.fit(xtrain,y3train)
ypred3=l.predict(xtest)
print(ypred3)
print("THE percentage SCORE OF FINDING THE BLOOD GROUP A+ In ram hospital IS")
q=(accuracy_score(y3test, ypred3))
print(q*100)


[1 1 1 1 1 1 1 1]
THE percentage SCORE OF FINDING THE BLOOD GROUP A+ In ram hospital IS
75.0


C:\anaconda\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [16]:
u=RandomForestClassifier(random_state=0)
u.fit(xtrain,y4train)
ypred4=u.predict(xtest)
print(ypred4)
print("THE percentage SCORE OF FINDING THE BLOOD GROUP A+ In ESI hospital IS")
g=(accuracy_score(y4test, ypred4))
print(g*100)


[1 1 1 1 1 1 1 1]
THE percentage SCORE OF FINDING THE BLOOD GROUP A+ In ESI hospital IS
62.5


C:\anaconda\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [17]:
a=RandomForestClassifier(random_state=0)
a.fit(xtrain,y5train)
ypred5=a.predict(xtest)
print(ypred5)
print("THE percentage SCORE OF FINDING THE BLOOD GROUP A+ In sarfdung hospital IS")
h=(accuracy_score(y5test, ypred5))
print(h*100)


[0 0 0 0 0 0 0 0]
THE percentage SCORE OF FINDING THE BLOOD GROUP A+ In sarfdung hospital IS
37.5


C:\anaconda\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [18]:
b=RandomForestClassifier(random_state=0)
b.fit(xtrain,y6train)
ypred6=b.predict(xtest)
print(ypred6)
print("THE percentage SCORE OF FINDING THE BLOOD GROUP A+ In SUCHETA KRIPLANI hospital IS")
i=(accuracy_score(y6test, ypred6))
print(i*100)


C:\anaconda\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


[0 0 0 0 0 0 0 0]
THE percentage SCORE OF FINDING THE BLOOD GROUP A+ In SUCHETA KRIPLANI hospital IS
50.0


In [19]:
y=RandomForestClassifier(random_state=0)
y.fit(xtrain,y7train)
ypred7=y.predict(xtest)
print(ypred7)
print("THE percentage SCORE OF FINDING THE BLOOD GROUP A+ In GOVIND BALLABH PANT hospital IS")
j=(accuracy_score(y7test, ypred7))
print(j*100)


[1 1 1 1 1 1 1 1]
THE percentage SCORE OF FINDING THE BLOOD GROUP A+ In GOVIND BALLABH PANT hospital IS
62.5


C:\anaconda\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [20]:
lr=RandomForestClassifier(random_state=0)
lr.fit(xtrain,y8train)
ypred8=lr.predict(xtest)
print(ypred8)
print("THE percentage SCORE OF FINDING THE BLOOD GROUP A+ In GURU TEGH BAHADUR hospital IS")
hg=(accuracy_score(y8test, ypred8))
print(hg*100)


C:\anaconda\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


[1 1 1 1 1 1 1 1]
THE percentage SCORE OF FINDING THE BLOOD GROUP A+ In GURU TEGH BAHADUR hospital IS
37.5


In [21]:
clr=RandomForestClassifier(random_state=0)
clr.fit(xtrain,y9train)
ypred9=clr.predict(xtest)
print(ypred9)
print("THE percentage SCORE OF FINDING THE BLOOD GROUP A+ In REGIONAL BLOOD TRANFUSION CENTRE CENTRAL ZONE  hospital IS")
hge=(accuracy_score(y9test, ypred9))
print(hge*100)


C:\anaconda\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


[1 1 1 1 1 1 1 1]
THE percentage SCORE OF FINDING THE BLOOD GROUP A+ In REGIONAL BLOOD TRANFUSION CENTRE CENTRAL ZONE  hospital IS
50.0
